name: regexrepro
version: 0.1.0.0
git: 'https://github.com/Hazelfire/regexrepro'
license: BSD3
author: 'Sam Nolan'
maintainer: 'samnolan555@gmail.com'
copyright: '2019 Sam Nolan'

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: ''

dependencies:
  - base >= 4.7 && < 5
  - regex-tdfa

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -Wmissing-export-lists
  - -Wpartial-fields

executables:
  regexrepro:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -optl--prog-name=regexrepro
    dependencies: []
